### ISSUE TITLE
undefined:62 Syntax error: Unexpected token ...

### ISSUE THREAD

**Issue by ikocev** [pmdartus/speedline#3]
When I run this tool I get this error:

```
speedline data.json
undefined:62
  this.children = new Map([...this.children.entries()].sort(sortingFunction))
                           ^^^
SyntaxError: Unexpected token ...
    at requireval (evalmachine.<anonymous>:13:39)
    at evalmachine.<anonymous>:50:1
    at new ModelAPI (/usr/local/lib/node_modules/speedline/node_modules/devtools-timeline-model/index.js:19:25)
    at Object.extractFramesFromTimeline (/usr/local/lib/node_modules/speedline/lib/frame.js:71:14)
    at module.exports (/usr/local/lib/node_modules/speedline/lib/index.js:42:25)
    at Object.<anonymous> (/usr/local/lib/node_modules/speedline/cli.js:73:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
$ node --version
v4.3.2
```

**Comment by sindresorhus** [comment]
[Node.js >=5 is required](https://github.com/pmdartus/speedline/blob/a23f1740856da0fc08d6b67fc7d4c47e840c544a/package.json#L14)

**Comment by pmdartus** [comment]
Thanks @ikocev, I just updated the `README` because it was still >= 4.0
